openapi: 3.0.4
info:
  title: Fonoaudiología Backend API
  version: 0.0.1
  description: API para el sistema de fonoaudiología

servers:
  - url: http://localhost:8000/api/v1
    description: Servidor de desarrollo local
  - url: https://tpi-fonoaudiologia-backend.onrender.com/api/v1
    description: Servidor de deploy en Render

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    profilesession:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token de sesión del perfil de usuario

  schemas:
    Error:
      type: object
      properties:
        status:
          type: string
          enum: [error]
        error:
          type: array
          items:
            type: string
    
    SceneObject:
      type: object
      required:
        - id
        - name
        - imageUrl
        - videoUrl
      properties:
        id:
          type: string
        name:
          type: string
        verticesLocation:
          type: array
          items:
            type: array
            items:
              type: number
        imageUrl:
          type: string
        videoUrl:
          type: string
        selectionId:
          type: string

    GameObject:
      allOf:
        - $ref: "#/components/schemas/SceneObject"
        - type: object
          required:
            - selectionId

    Game:
      type: object
      properties:
        videoUrl:
          type: string
        objects:
          type: array
          items:
            $ref: "#/components/schemas/GameObject"

    GetGamesResponse:
      type: object
      properties:
        status:
          type: string
          enum: [ok, error]
        games_data:
          type: array
          items:
            $ref: '#/components/schemas/Game'
        error:
          type: array
          items:
            type: string

    CheckGameResult:
      type: object
      properties:
        status:
          type: string
          enum: [ok, error]
        scene_id:
          type: string
        is_correct:
          type: boolean
        object_name:
          type: string
        error:
          type: array
          items:
            type: string

    SelectProfileResponse:
      type: object
      properties:
        message:
          type: string
        token:
          type: string
          description: Token de sesión del perfil de usuario

    Profile:
      type: object
      required:
        - id
        - name
        - avatar_url
      properties:
        id:
          type: string
        name:
          type: string
        avatar_url:
          type: string

    GetProfilesResponse:
      type: object
      required:
        - profiles
      properties:
        profiles:
          type: array
          items:
            $ref: '#/components/schemas/Profile'

    Scene:
      type: object
      required:
        - id
        - nombre
        - descripcion
        - imagenUrl
        - logoUrl
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        nombre:
          type: string
        descripcion:
          type: string
          nullable: true
        imagenUrl:
          type: string
        logoUrl:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    GetScenesResponse:
      type: array
      items:
        $ref: '#/components/schemas/Scene'

    CreateSceneRequest:
      type: object
      properties:
        nombre:
          type: string
        descripcion:
          type: string
          nullable: true
        imagenUrl:
          type: string
        logoUrl:
          type: string
      required:
        - nombre
        - imagenUrl
        - logoUrl

    CreateSceneResponse:
      type: object
      properties:
        status:
          type: string
          enum: [ok, error]
        scene:
          $ref: '#/components/schemas/Scene'
        error:
          type: array
          items:
            type: string

    ProgresedScene:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string

    GameSession:
      type: object
      required:
        - intento
        - aciertos
        - totalPreguntas
        - tiempoCompletado
      properties:
        intento:
          type: integer
        aciertos:
          type: integer
        totalPreguntas:
          type: integer
        tiempoCompletado:
          type: integer

    GetProgressedScenesResponse:
      type: object
      properties:
        status:
          type: string
          enum: [ok, error]
        scenes_with_progress:
          type: array
          items:
            $ref: '#/components/schemas/ProgresedScene'
        error:
          type: array
          items:
            type: string

    GetSceneProgressResponse:
      type: object
      properties:
        status:
          type: string
          enum: [ok, error]
        scenes_game_sessions:
          type: array
          items:
            $ref: '#/components/schemas/GameSession'
        error:
          type: array
          items:
            type: string

paths:
  /games/{sceneId}:
    get:
      operationId: getGames
      tags:
        - Games
      summary: Obtiene los juegos para un escenario específico
      security:
        - bearerAuth: []
      parameters:
        - name: sceneId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Juegos obtenidos exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGamesResponse'
        '404':
          description: Escenario no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /games/submitSelection/{selectionId}:
    post:
      operationId: submitSelection
      tags:
        - Games
      summary: Verifica si la selección del usuario es correcta
      security:
        - bearerAuth: []
      parameters:
        - name: selectionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Resultado verificado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckGameResult'
        '406':
          description: Token no válido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/getProfiles:
    get:
      operationId: getUserProfiles
      tags:
        - User
      summary: Obtiene los perfiles del usuario
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Perfiles obtenidos exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProfilesResponse'

  /user/progress/getProgressedScenes:
    get:
      operationId: getProgressedScenes
      tags:
        - Progress
      summary: Obtiene los escenarios con progreso del perfil actual
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Escenarios con progreso obtenidos exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProgressedScenesResponse'
        '401':
          description: No autorizado - Perfil no seleccionado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/progress/{sceneId}:
    get:
      operationId: getSceneProgress
      tags:
        - Progress
      summary: Obtiene el progreso de un escenario específico
      security:
        - bearerAuth: []
      parameters:
        - name: sceneId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Progreso del escenario obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSceneProgressResponse'
        '400':
          description: ID de escena no proporcionado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: No autorizado - Perfil no seleccionado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/selectProfile:
    post:
      operationId: selectUserProfile
      tags:
        - User
      summary: Selecciona un perfil de usuario
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                profile_id:
                  type: string
              required:
                - profile_id
      responses:
        '200':
          description: Perfil seleccionado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SelectProfileResponse'
        '404':
          description: Perfil no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /editProfile/{profileId}:
    put:
      operationId: editUserProfile
      tags:
        - User
      summary: Edita un perfil de usuario existente
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                avatar_url:
                  type: string
              required:
                - name
      responses:
        '200':
          description: Perfil editado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '404':
          description: Perfil no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /deleteProfile/{profileId}:
    delete:
      operationId: deleteUserProfile
      tags:
        - User
      summary: Elimina un perfil de usuario
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Perfil eliminado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile deleted successfully"
        '404':
          description: Perfil no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /scenes/{id}:
    get:
      operationId: getScene
      tags:
        - Scenes
      summary: Obtiene un escenario específico
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Escenario obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scene'
        '404':
          description: Escenario no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /scenes:
    get:
      operationId: getScenes
      tags:
        - Scenes
      summary: Obtiene todos los escenarios
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de escenarios obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetScenesResponse'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Scenes
      summary: Crea un nuevo escenario
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSceneRequest'
      responses:
        '201':
          description: Escenario creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSceneResponse'
        '400':
          description: Datos inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /objects/{id}:
    get:
      tags:
        - Objects
      summary: Obtiene un objeto de escenario específico
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Objeto de escenario obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SceneObject'
        '400':
          description: ID no proporcionado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Objeto de escenario no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /objects:
    post:
      tags:
        - Objects
      summary: Crea un nuevo objeto de escenario
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SceneObject'
      responses:
        '201':
          description: Objeto de escenario creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SceneObject'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
